### PR TITLE
various renamings

### PR DESCRIPTION
**Pull request by pelikhan**
I've gone through the repo and made some alignement with the naming conventions of PXT.

- [x] camelizing APIs
- [x] splitting servo/motor in different files
- [x] providing default values to parameters in place
- [x] started to fill up README.md
- [x] add icon.png

### CODE REVIEW

**Comment by KitronikLtd** [comment]
@pelikhan where is the icon used? We have a Kitronik micro:bit icon that we have designed for the boards and the instruction books.

**Review by DaveAtKitronik — APPROVED** [review]
These changes are ok. 
Might prompt the moving of the none ServoLite code to another blocks repo - That would allow a cleaner readme.md and tests

**Review by DaveAtKitronik — APPROVED** [review]
That's the correct green :)

**Review by DaveAtKitronik — APPROVED** [review]
Not sure where this icon is used, but that is the Kitronik line follower buggy for micro:bit, so a reasonable first icon

**Pull request merged**
